alias bi='bundle install'
alias cc='claude --dangerously-skip-permissions'
alias cx='codex --yolo'
alias gs='git status'
alias l='eza -lah --group-directories-first'
alias ll='eza -lh --group-directories-first'
